name: For Wild Music
favicon: null
layout_spectrum: 0.12672912771813571
typography_spectrum: 0.9554649638012052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9713497417978942
  lightness: 0.5950717884115875
  saturation: 0.23971074889414012
  rhythmicContrast: 0.9604465034790337
purpose: []
